language: java

sudo: false

jdk:
  - oraclejdk8

script:
./generate_float_code.sh
mvn -P travis -X -pl :ezfftw clean test jacoco:report

after_success:
- mvn -P coveralls -pl :ezfftw -DrepoToken=$COVERALLS_TOKEN coveralls:report