language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
- bash ./remove_float_code.sh || true
- bash ./generate_float_code.sh

script: mvn -P travis -X -pl :ezfftw clean test jacoco:report

after_success:
- mvn -P coveralls -pl :ezfftw -DrepoToken=$COVERALLS_TOKEN coveralls:report