language: java

sudo: false

jdk:
  - oraclejdk8

script: mvn -P travis -X -pl :ezfftw clean test jacoco:report

after_success:
- mvn -pl -P coveralls :ezfftw -DrepoToken=$COVERALLS_TOKEN coveralls:report